In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [16]:
### One Hot Representation:
for words in sent:
    print(words)
    print(one_hot(words,voc_size))
    print("")

one_hot_repr=[one_hot(words,voc_size)for words in sent]

the glass of milk
[558, 7578, 7660, 2164]

the glass of juice
[558, 7578, 7660, 3731]

the cup of tea
[558, 2801, 7660, 7151]

I am a good boy
[1663, 8442, 357, 3950, 1217]

I am a good developer
[1663, 8442, 357, 3950, 8233]

understand the meaning of words
[8386, 558, 7635, 7660, 320]

your videos are good
[6717, 6411, 9017, 3950]



In [12]:
## Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length )
print(embedded_docs)

[[   0    0    0    0  558 7578 7660 2164]
 [   0    0    0    0  558 7578 7660 3731]
 [   0    0    0    0  558 2801 7660 7151]
 [   0    0    0 1663 8442  357 3950 1217]
 [   0    0    0 1663 8442  357 3950 8233]
 [   0    0    0 8386  558 7635 7660  320]
 [   0    0    0    0 6717 6411 9017 3950]]


In [18]:
#feature representation
dim=10


In [19]:
## Creating model
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')


2025-03-24 12:44:12.123373: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2025-03-24 12:44:12.123551: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-03-24 12:44:12.124051: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2025-03-24 12:44:12.125039: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-03-24 12:44:12.125643: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

2025-03-24 12:45:00.009932: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 1s 522ms/step


array([[[ 0.00973717,  0.03033561,  0.04328305,  0.02812516,
          0.04962214, -0.02463299,  0.03209991,  0.02985014,
         -0.01581568,  0.04584557],
        [ 0.00973717,  0.03033561,  0.04328305,  0.02812516,
          0.04962214, -0.02463299,  0.03209991,  0.02985014,
         -0.01581568,  0.04584557],
        [ 0.00973717,  0.03033561,  0.04328305,  0.02812516,
          0.04962214, -0.02463299,  0.03209991,  0.02985014,
         -0.01581568,  0.04584557],
        [ 0.00973717,  0.03033561,  0.04328305,  0.02812516,
          0.04962214, -0.02463299,  0.03209991,  0.02985014,
         -0.01581568,  0.04584557],
        [-0.03379019, -0.02202965, -0.03002365, -0.02477657,
         -0.00918568, -0.02860468,  0.01457271,  0.01411765,
          0.01857258, -0.02541825],
        [-0.01752587,  0.03419763,  0.02038867,  0.0346365 ,
          0.03575233, -0.03099452, -0.00993078, -0.0232217 ,
          0.03968931, -0.01228952],
        [ 0.0093207 ,  0.04254545, -0.01239632, -0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0,  558, 7578, 7660, 2164], dtype=int32)

In [32]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 20ms/step


array([[ 0.00973717,  0.03033561,  0.04328305,  0.02812516,  0.04962214,
        -0.02463299,  0.03209991,  0.02985014, -0.01581568,  0.04584557],
       [ 0.00973717,  0.03033561,  0.04328305,  0.02812516,  0.04962214,
        -0.02463299,  0.03209991,  0.02985014, -0.01581568,  0.04584557],
       [ 0.00973717,  0.03033561,  0.04328305,  0.02812516,  0.04962214,
        -0.02463299,  0.03209991,  0.02985014, -0.01581568,  0.04584557],
       [ 0.00973717,  0.03033561,  0.04328305,  0.02812516,  0.04962214,
        -0.02463299,  0.03209991,  0.02985014, -0.01581568,  0.04584557],
       [-0.03379019, -0.02202965, -0.03002365, -0.02477657, -0.00918568,
        -0.02860468,  0.01457271,  0.01411765,  0.01857258, -0.02541825],
       [-0.01752587,  0.03419763,  0.02038867,  0.0346365 ,  0.03575233,
        -0.03099452, -0.00993078, -0.0232217 ,  0.03968931, -0.01228952],
       [ 0.0093207 ,  0.04254545, -0.01239632, -0.02673684,  0.01520718,
        -0.03609294, -0.0052707 ,  0.04073404